name: Deploy via FTPS (Active24)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ⬇️ KLÍČOVÉ: zahodíme lock z macOS a nainstalujeme pro Linux
      - name: Clean lockfile for Linux install
        run: rm -f package-lock.json

      - name: Install deps (fresh)
        run: npm install --no-audit --fund=false

      - name: Build (SvelteKit static)
        run: npm run build

      - name: Deploy to Active24 via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: build/
          server-dir: /plynule.com/web/
          exclude: |
            **/.git*
            **/node_modules/**
            **/.svelte-kit/**